package in.shoksworld.greendao.storage.dbgenerator;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import in.shoksworld.greendao.storage.dbgenerator.VEHICLE;

import in.shoksworld.greendao.storage.dbgenerator.VEHICLEDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vEHICLEDaoConfig;

    private final VEHICLEDao vEHICLEDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vEHICLEDaoConfig = daoConfigMap.get(VEHICLEDao.class).clone();
        vEHICLEDaoConfig.initIdentityScope(type);

        vEHICLEDao = new VEHICLEDao(vEHICLEDaoConfig, this);

        registerDao(VEHICLE.class, vEHICLEDao);
    }
    
    public void clear() {
        vEHICLEDaoConfig.clearIdentityScope();
    }

    public VEHICLEDao getVEHICLEDao() {
        return vEHICLEDao;
    }

}
