package in.shoksworld.greendao.storage.dbgenerator;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "VEHICLE".
 */
@Entity
public class VEHICLE {

    @Id
    private Long id;
    private String vehicleName;
    private String vehicleType;
    private Integer price;

    @Generated
    public VEHICLE() {
    }

    public VEHICLE(Long id) {
        this.id = id;
    }

    @Generated
    public VEHICLE(Long id, String vehicleName, String vehicleType, Integer price) {
        this.id = id;
        this.vehicleName = vehicleName;
        this.vehicleType = vehicleType;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVehicleName() {
        return vehicleName;
    }

    public void setVehicleName(String vehicleName) {
        this.vehicleName = vehicleName;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

}
