package in.shoksworld.greendao.storage.dbgenerator;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VEHICLE".
*/
public class VEHICLEDao extends AbstractDao<VEHICLE, Long> {

    public static final String TABLENAME = "VEHICLE";

    /**
     * Properties of entity VEHICLE.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VehicleName = new Property(1, String.class, "vehicleName", false, "VEHICLE_NAME");
        public final static Property VehicleType = new Property(2, String.class, "vehicleType", false, "VEHICLE_TYPE");
        public final static Property Price = new Property(3, Integer.class, "price", false, "PRICE");
    }


    public VEHICLEDao(DaoConfig config) {
        super(config);
    }
    
    public VEHICLEDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VEHICLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VEHICLE_NAME\" TEXT," + // 1: vehicleName
                "\"VEHICLE_TYPE\" TEXT," + // 2: vehicleType
                "\"PRICE\" INTEGER);"); // 3: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VEHICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VEHICLE entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vehicleName = entity.getVehicleName();
        if (vehicleName != null) {
            stmt.bindString(2, vehicleName);
        }
 
        String vehicleType = entity.getVehicleType();
        if (vehicleType != null) {
            stmt.bindString(3, vehicleType);
        }
 
        Integer price = entity.getPrice();
        if (price != null) {
            stmt.bindLong(4, price);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VEHICLE entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vehicleName = entity.getVehicleName();
        if (vehicleName != null) {
            stmt.bindString(2, vehicleName);
        }
 
        String vehicleType = entity.getVehicleType();
        if (vehicleType != null) {
            stmt.bindString(3, vehicleType);
        }
 
        Integer price = entity.getPrice();
        if (price != null) {
            stmt.bindLong(4, price);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VEHICLE readEntity(Cursor cursor, int offset) {
        VEHICLE entity = new VEHICLE( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // vehicleName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // vehicleType
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VEHICLE entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVehicleName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVehicleType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VEHICLE entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VEHICLE entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VEHICLE entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
